package de.christianbreitkreutz;

public class UriScheme {
	// source: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
	public static final String AAA = "aaa"; // Diameter Protocol
	public static final String AAAS = "aaas"; // Diameter Protocol with Secure Transport
	public static final String ABOUT = "about"; // about
	public static final String ACAP = "acap"; // application configuration access protocol
	public static final String ACCT = "acct"; // acct
	public static final String ACR = "acr"; // acr
	public static final String ADIUMXTRA = "adiumxtra"; // adiumxtra
	public static final String AFP = "afp"; // afp
	public static final String AFS = "afs"; // Andrew File System global file names
	public static final String AIM = "aim"; // aim
	public static final String APPDATA = "appdata"; // appdata
	public static final String APT = "apt"; // apt
	public static final String ATTACHMENT = "attachment"; // attachment
	public static final String AW = "aw"; // aw
	public static final String BARION = "barion"; // barion
	public static final String BESHARE = "beshare"; // beshare
	public static final String BITCOIN = "bitcoin"; // bitcoin
	public static final String BLOB = "blob"; // blob
	public static final String BOLO = "bolo"; // bolo
	public static final String BROWSEREXT = "browserext"; // browserext
	public static final String CALLTO = "callto"; // callto
	public static final String CAP = "cap"; // Calendar Access Protocol
	public static final String CHROME = "chrome"; // chrome
	public static final String CHROME_EXTENSION = "chrome-extension"; // chrome-extension
	public static final String CID = "cid"; // content identifier
	public static final String COAP = "coap"; // coap
	public static final String COAPS = "coaps"; // coaps
	public static final String COM_EVENTBRITE_ATTENDEE = "com-eventbrite-attendee"; // com-eventbrite-attendee
	public static final String CONTENT = "content"; // content
	public static final String CRID = "crid"; // TV-Anytime Content Reference Identifier
	public static final String CVS = "cvs"; // cvs
	public static final String DATA = "data"; // data
	public static final String DAV = "dav"; // dav
	public static final String DICT = "dict"; // dictionary service protocol
	public static final String DIS = "dis"; // dis
	public static final String DLNA_PLAYCONTAINER = "dlna-playcontainer"; // dlna-playcontainer
	public static final String DLNA_PLAYSINGLE = "dlna-playsingle"; // dlna-playsingle
	public static final String DNS = "dns"; // Domain Name System
	public static final String DNTP = "dntp"; // dntp
	public static final String DTN = "dtn"; // DTNRG research and development
	public static final String DVB = "dvb"; // dvb
	public static final String ED2K = "ed2k"; // ed2k
	public static final String EXAMPLE = "example"; // example
	public static final String FACETIME = "facetime"; // facetime
	public static final String FAX = "fax"; // fax
	public static final String FEED = "feed"; // feed
	public static final String FEEDREADY = "feedready"; // feedready
	public static final String FILE = "file"; // Host-specific file names
	public static final String FILESYSTEM = "filesystem"; // filesystem
	public static final String FINGER = "finger"; // finger
	public static final String FISH = "fish"; // fish
	public static final String FTP = "ftp"; // File Transfer Protocol
	public static final String GEO = "geo"; // Geographic Locations
	public static final String GG = "gg"; // gg
	public static final String GIT = "git"; // git
	public static final String GIZMOPROJECT = "gizmoproject"; // gizmoproject
	public static final String GO = "go"; // go
	public static final String GOPHER = "gopher"; // The Gopher Protocol
	public static final String GTALK = "gtalk"; // gtalk
	public static final String H323 = "h323"; // H.323
	public static final String HAM = "ham"; // ham
	public static final String HCP = "hcp"; // hcp
	public static final String HTTP = "http"; // Hypertext Transfer Protocol
	public static final String HTTPS = "https"; // Hypertext Transfer Protocol Secure
	public static final String HYDRAZONE = "hydrazone"; // hydrazone
	public static final String IAX = "iax"; // Inter-Asterisk eXchange Version 2
	public static final String ICAP = "icap"; // Internet Content Adaptation Protocol
	public static final String ICON = "icon"; // icon
	public static final String IM = "im"; // Instant Messaging
	public static final String IMAP = "imap"; // iotdisco
	public static final String IPN = "ipn"; // ipn
	public static final String IPP = "ipp"; // Internet Printing Protocol
	public static final String IPPS = "ipps"; // Internet Printing Protocol over HTTPS
	public static final String IRC = "irc"; // irc
	public static final String IRC6 = "irc6"; // irc6
	public static final String IRCS = "ircs"; // ircs
	public static final String IRIS = "iris"; // Internet Registry Information Service
	public static final String IRISBEEP = "iris.beep"; // iris.beep
	public static final String IRISLWZ = "iris.lwz"; // iris.lwz
	public static final String IRISXPC = "iris.xpc"; // iris.xpc
	public static final String IRISXPCS = "iris.xpcs"; // iris.xpcs
	public static final String ISOSTORE = "isostore"; // isostore
	public static final String ITMS = "itms"; // itms
	public static final String JABBER = "jabber"; // jabber
	public static final String JAR = "jar"; // jar
	public static final String JMS = "jms"; // Java Message Service
	public static final String KEYPARC = "keyparc"; // keyparc
	public static final String LASTFM = "lastfm"; // lastfm
	public static final String LDAP = "ldap"; // Lightweight Directory Access Protocol
	public static final String LDAPS = "ldaps"; // ldaps
	public static final String LVLT = "lvlt"; // lvlt
	public static final String MAGNET = "magnet"; // magnet
	public static final String MAILSERVER = "mailserver"; // Access to data available from mail servers
	public static final String MAILTO = "mailto"; // Electronic mail address
	public static final String MAPS = "maps"; // maps
	public static final String MARKET = "market"; // market
	public static final String MESSAGE = "message"; // message
	public static final String MID = "mid"; // message identifier
	public static final String MMS = "mms"; // mms
	public static final String MODEM = "modem"; // modem
	public static final String MOZ = "moz"; // moz
	public static final String MS_ACCESS = "ms-access"; // ms-access
	public static final String MS_BROWSER_EXTENSION = "ms-browser-extension"; // ms-browser-extension
	public static final String MS_DRIVE_TO = "ms-drive-to"; // ms-drive-to
	public static final String MS_ENROLLMENT = "ms-enrollment"; // ms-enrollment
	public static final String MS_EXCEL = "ms-excel"; // ms-excel
	public static final String MS_GAMEBARSERVICES = "ms-gamebarservices"; // ms-gamebarservices
	public static final String MS_GETOFFICE = "ms-getoffice"; // ms-getoffice
	public static final String MS_HELP = "ms-help"; // ms-help
	public static final String MS_INFOPATH = "ms-infopath"; // ms-infopath
	public static final String MS_MEDIA_STREAM_ID = "ms-media-stream-id"; // ms-media-stream-id
	public static final String MS_OFFICEAPP = "ms-officeapp"; // ms-officeapp
	public static final String MS_PROJECT = "ms-project"; // ms-project
	public static final String MS_POWERPOINT = "ms-powerpoint"; // ms-powerpoint
	public static final String MS_PUBLISHER = "ms-publisher"; // ms-publisher
	public static final String MS_SEARCH_REPAIR = "ms-search-repair"; // ms-search-repair
	public static final String MS_SECONDARY_SCREEN_CONTROLLER = "ms-secondary-screen-controller"; // ms-secondary-screen-controller
	public static final String MS_SECONDARY_SCREEN_SETUP = "ms-secondary-screen-setup"; // ms-secondary-screen-setup
	public static final String MS_SETTINGS = "ms-settings"; // ms-settings
	public static final String MS_SETTINGS_AIRPLANEMODE = "ms-settings-airplanemode"; // ms-settings-airplanemode
	public static final String MS_SETTINGS_BLUETOOTH = "ms-settings-bluetooth"; // ms-settings-bluetooth
	public static final String MS_SETTINGS_CAMERA = "ms-settings-camera"; // ms-settings-camera
	public static final String MS_SETTINGS_CELLULAR = "ms-settings-cellular"; // ms-settings-cellular
	public static final String MS_SETTINGS_CLOUDSTORAGE = "ms-settings-cloudstorage"; // ms-settings-cloudstorage
	public static final String MS_SETTINGS_CONNECTABLEDEVICES = "ms-settings-connectabledevices"; // ms-settings-connectabledevices
	public static final String MS_SETTINGS_DISPLAYS_TOPOLOGY = "ms-settings-displays-topology"; // ms-settings-displays-topology
	public static final String MS_SETTINGS_EMAILANDACCOUNTS = "ms-settings-emailandaccounts"; // ms-settings-emailandaccounts
	public static final String MS_SETTINGS_LANGUAGE = "ms-settings-language"; // ms-settings-language
	public static final String MS_SETTINGS_LOCATION = "ms-settings-location"; // ms-settings-location
	public static final String MS_SETTINGS_LOCK = "ms-settings-lock"; // ms-settings-lock
	public static final String MS_SETTINGS_NFCTRANSACTIONS = "ms-settings-nfctransactions"; // ms-settings-nfctransactions
	public static final String MS_SETTINGS_NOTIFICATIONS = "ms-settings-notifications"; // ms-settings-notifications
	public static final String MS_SETTINGS_POWER = "ms-settings-power"; // ms-settings-power
	public static final String MS_SETTINGS_PRIVACY = "ms-settings-privacy"; // ms-settings-privacy
	public static final String MS_SETTINGS_PROXIMITY = "ms-settings-proximity"; // ms-settings-proximity
	public static final String MS_SETTINGS_SCREENROTATION = "ms-settings-screenrotation"; // ms-settings-screenrotation
	public static final String MS_SETTINGS_WIFI = "ms-settings-wifi"; // ms-settings-wifi
	public static final String MS_SETTINGS_WORKPLACE = "ms-settings-workplace"; // ms-settings-workplace
	public static final String MS_SPD = "ms-spd"; // ms-spd
	public static final String MS_STTOVERLAY = "ms-sttoverlay"; // ms-sttoverlay
	public static final String MS_TRANSIT_TO = "ms-transit-to"; // ms-transit-to
	public static final String MS_VIRTUALTOUCHPAD = "ms-virtualtouchpad"; // ms-virtualtouchpad
	public static final String MS_VISIO = "ms-visio"; // ms-visio
	public static final String MS_WALK_TO = "ms-walk-to"; // ms-walk-to
	public static final String MS_WORD = "ms-word"; // ms-word
	public static final String MSNIM = "msnim"; // msnim
	public static final String MSRP = "msrp"; // Message Session Relay Protocol
	public static final String MSRPS = "msrps"; // Message Session Relay Protocol Secure
	public static final String MTQP = "mtqp"; // Message Tracking Query Protocol
	public static final String MUMBLE = "mumble"; // mumble
	public static final String MUPDATE = "mupdate"; // Mailbox Update (MUPDATE) Protocol
	public static final String MVN = "mvn"; // mvn
	public static final String NEWS = "news"; // USENET news
	public static final String NFS = "nfs"; // network file system protocol
	public static final String NI = "ni"; // ni
	public static final String NIH = "nih"; // nih
	public static final String NNTP = "nntp"; // USENET news using NNTP access
	public static final String NOTES = "notes"; // notes
	public static final String OCF = "ocf"; // ocf
	public static final String OID = "oid"; // oid
	public static final String OPAQUELOCKTOKEN = "opaquelocktoken"; // opaquelocktokent
	public static final String PACK = "pack"; // pack
	public static final String PALM = "palm"; // palm
	public static final String PAPARAZZI = "paparazzi"; // paparazzi
	public static final String PKCS11 = "pkcs11"; // PKCS#11
	public static final String PLATFORM = "platform"; // platform
	public static final String POP = "pop"; // Post Office Protocol v3
	public static final String PRES = "pres"; // Presence
	public static final String PROSPERO = "prospero"; // Prospero Directory Service
	public static final String PROXY = "proxy"; // proxy
	public static final String PWID = "pwid"; // pwid
	public static final String PSYC = "psyc"; // psyc
	public static final String QB = "qb"; // qb
	public static final String QUERY = "query"; // query
	public static final String REDIS = "redis"; // redis
	public static final String REDISS = "rediss"; // rediss
	public static final String RELOAD = "reload"; // reload
	public static final String RES = "res"; // res
	public static final String RESOURCE = "resource"; // resource
	public static final String RMI = "rmi"; // rmi
	public static final String RSYNC = "rsync"; // rsync
	public static final String RTMFP = "rtmfp"; // rtmfp
	public static final String RTMP = "rtmp"; // rtmp
	public static final String RTSP = "rtsp"; // Real-Time Streaming Protocol (RTSP)
	public static final String RTSPS = "rtsps"; // Real-Time Streaming Protocol (RTSP) over TLS
	public static final String RTSPU = "rtspu"; // (RTSP) over unreliable datagram transport
	public static final String SECONDLIFE = "secondlife"; // query
	public static final String SERVICE = "service"; // service location
	public static final String SESSION = "session"; // session
	public static final String SFTP = "sftp"; // query
	public static final String SGN = "sgn"; // sgn
	public static final String SHTTP = "shttp"; // Secure Hypertext Transfer Protocol
	public static final String SIEVE = "sieve"; // ManageSieve Protocol
	public static final String SIP = "sip"; // session initiation protocol
	public static final String SIPS = "sips"; // secure session initiation protocol
	public static final String SKYPE = "skype"; // skype
	public static final String SMB = "smb"; // smb
	public static final String SMS = "sms"; // Short Message Service
	public static final String SMTP = "smtp"; // smtp
	public static final String SNEWS = "snews"; // NNTP over SSL/TLS
	public static final String SNMP = "snmp"; // Simple Network Management Protocol
	public static final String SOAPBEEP = "soap.beep"; // soap.beep
	public static final String SOAPBEEPS = "soap.beeps"; // soap.beeps
	public static final String SOLDAT = "soldat"; // soldat
	public static final String SPOTIFY = "spotify"; // spotify
	public static final String SSH = "ssh"; // ssh
	public static final String STEAM = "steam"; // steam
	public static final String STUN = "stun"; // stun
	public static final String STUNS = "stuns"; // stuns
	public static final String SUBMIT = "submit"; // submit
	public static final String SVN = "svn"; // svn
	public static final String TAG = "tag"; // tag
	public static final String TEAMSPEAK = "teamspeak"; // teamspeak
	public static final String TEL = "tel"; // telephone
	public static final String TELIAEID = "teliaeid"; // teliaeid
	public static final String TELNET = "telnet"; // Reference to interactive sessions
	public static final String TFTP = "tftp"; // Trivial File Transfer Protocol
	public static final String THINGS = "things"; // things
	public static final String THISMESSAGE = "thismessage"; // multipart/related relative reference resolution
	public static final String TIP = "tip"; // Transaction Internet Protocol
	public static final String TN3270 = "tn3270"; // Interactive 3270 emulation sessions
	public static final String TOOL = "tool"; // tool
	public static final String TURN = "turn"; // turn
	public static final String TURNS = "turns"; // turns
	public static final String TV = "tv"; // TV Broadcasts
	public static final String UDP = "udp"; // udp
	public static final String UNREAL = "unreal"; // unreal
	public static final String URN = "urn"; // Uniform Resource Names
	public static final String UT2004 = "ut2004"; // ut2004
	public static final String V_EVENT = "v-event"; // v-event
	public static final String VEMMI = "vemmi"; // versatile multimedia interface
	public static final String VENTRILO = "ventrilo"; // ventrilo
	public static final String VIDEOTEX = "videotex"; // videotex
	public static final String VNC = "vnc"; // Remote Framebuffer Protocol
	public static final String VIEW_SOURCE = "view-source"; // view-source
	public static final String WAIS = "wais"; // Wide Area Information Servers
	public static final String WEBCAL = "webcal"; // webcal
	public static final String WPID = "wpid"; // wpid
	public static final String WS = "ws"; // WebSocket connections
	public static final String WSS = "wss"; // Encrypted WebSocket connections
	public static final String WTAI = "wtai"; // wtai
	public static final String WYCIWYG = "wyciwyg"; // wyciwyg
	public static final String XCON = "xcon"; // xcon
	public static final String XCON_USERID = "xcon-userid"; // xcon-userid
	public static final String XFIRE = "xfire"; // xfire
	public static final String XMLRPCBEEP = "xmlrpc.beep"; // xmlrpc.beep
	public static final String XMLRPCBEEPS = "xmlrpc.beeps"; // xmlrpc.beeps
	public static final String XMPP = "xmpp"; // Extensible Messaging and Presence Protocol
	public static final String XRI = "xri"; // xri
	public static final String YMSGR = "ymsgr"; // ymsgr
	public static final String Z3950 = "z39.50"; // Z39.50 information access
	public static final String Z3950R = "z39.50r"; // Z39.50 Retrieval
	public static final String Z3950S = "z39.50s"; // Z39.50 Session
}